F creacion edicion members ot105 35
alkemyTech/OT105-Client pull request #15
Opened 2021-11-29 23:14 UTC by pdvallejos

Summary:
creacion de ruta y componente para el backoffice/members/edit para la creacion y edicion de miembros.

Link: https://alkemy-labs.atlassian.net/browse/OT105-35

Changes added:
se agrega ruta el archivo app mencionada anteriormente
se agrega archivo MembersCreateEdit.js a la carpeta Members

![image](https://user-images.githubusercontent.com/82845564/143957538-02f5f622-5e6f-43f2-9208-7993f0cd69db.png)

2021-12-07 22:32 UTC, saralavanchy commented
Please clean the title to be clear

2021-12-07 22:55 UTC, saralavanchy requested changes

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +  const [initialValues, setInitialValues] = useState({
please use a mor specif name, initialValues is too generic and do not give information about its content. Maybe member is a more specific name

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +};
please move this style to Styles folder

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +  const urlCreate = `http://ongapi.alkemy.org/public/api/members`;
this both Url should be here, they should be on memeberService

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +  const [files, setFiles] = useState([]);
what this files are for? files are a too generic name. Please use one more specific

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +  const [files, setFiles] = useState([]);
what this files are for? files are a too generic name. Please use one more specific

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +      });
what is being done inside of setInitialValues, image? The answer of that question is a good candidate for the name of the function where this peace of code should be. Please move this to a separated function and then call it here.
```
const getImageWithUrl= (acceptedFiles) => acceptedFiles.map((file) =>
          Object.assign(file, {
            preview: URL.createObjectURL(file),
          }),
        );
```
then on the onFileDrop fuction
```
setInitialValues({...initialValue, image: getFilesWithUrl(acceptedFiles)})
```

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +        ),
same about getImageWithUrl

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +  const thumbs = files.map((file) => (
please use a more specific name

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +      // Make sure to revoke the data uris to avoid memory leaks
please delete this comment, the code should be enought documentation for itself

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +      files.forEach((file) => URL.revokeObjectURL(file.preview));
move this to a function outside the useEffect
```
const avoidMemoryLeak = () =>  files.forEach((file) => URL.revokeObjectURL(file.preview));
```

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +  };
for name, facebook and linkedin you should create only one onChange and use a switch on it

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +    const datosSinEtiquetas = datosConEtiquetas.replace(/<[^>]+>/g, '');
move the replace into a function "cleanTags"

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +    }
all this should be on MembersService

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +    };
please move this to a function outside the useEffect. Also dataEdit do not describe what is being done here. Please update the name to something like loadMemberInfoOnEdit

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +        //Name
The code should be enought documentation to itself, please delete this comment

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +        //Image
The code should be enought documentation to itself, please delete this comment

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +        //Description
The code should be enought documentation to itself, please delete this comment

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/Members/MembersCreateEdit.js
> +              <ErrorMessage
please create a function to show Errors
```
const showErrors = (attribute) => (<ErrorMessage
                component={() => (
                  <Alert severity="warning">{errors[attribute]}</Alert>
                )}
                name="name"
              />)
```

2021-12-07 22:55 UTC, saralavanchy commented on src/Components/News/NewsCreateEdit.js
> +//eslint-disable react-hooks/exhaustive-deps
This file is not scope of this user story

2021-12-08 21:45 UTC, pdvallejos commented on src/Components/Members/MembersCreateEdit.js
> +      });
Sara de la manera que lo he cambiado  para tratar de sacarlo siempre me tira error o en los map o sino me tira este error
![image](https://user-images.githubusercontent.com/82845564/145263891-e006478a-272d-4e1c-a548-ab3bd4b40a9c.png)

2021-12-13 22:13 UTC, saralavanchy approved these changes

2021-12-15 11:13 UTC, merged