OT105-81/Extend HTTP base service for Slides requests
alkemyTech/OT105-Client pull request #23
Opened 2021-12-02 19:06 UTC by facundo-91

## Summary
Created service with necessary axios methods for add/update/delete/get slides. Also methods for converting uploaded image to base64 and retrieved image from URL to blob.

## Jira link
[OT105-81](https://alkemy-labs.atlassian.net/browse/OT105-81)

## Changes added
- add SlideFormService.js

## Screenshots
![Screenshot from 2021-12-02 16-04-24](https://user-images.githubusercontent.com/36646957/144486471-2e78d6bd-e638-44a8-9c91-99058eaba1aa.png)
![Screenshot from 2021-12-02 16-02-50](https://user-images.githubusercontent.com/36646957/144486556-901194fe-fa17-495a-b907-77a77ff14d8c.png)

2021-12-07 23:20 UTC, saralavanchy approved these changes

2021-12-07 23:22 UTC, saralavanchy requested changes
please update the slides component to instead of receive mock data use get function from this service

2021-12-07 23:30 UTC, facundo-91 commented
it already does

2021-12-14 14:50 UTC, saralavanchy approved these changes

2021-12-14 14:51 UTC, merged